shaders:
  - name: default shader
    vertexShader: "resource/shader/default_vs.glsl"
    fragmentShader: "resource/shader/default_fs.glsl"
    attributes:
      vertexPosition:
        name: "vertexPosition"
        defaultLoc: 0
        indexInLocArray: 0
        type: "vec3"
      vertexCoord:
        name: "vertexTexCoord"
        defaultLoc: 1
        indexInLocArray: 1
        type: "vec2"
      vertexColor:
        name: "vertexColor"
        defaultLoc: 2
        indexInLocArray: 2
        type: "vec4"
    uniforms:
      mvp:
        name: "mvp"
        type: "mat4"
        indexInLocArray: 3